{% set name = "qastle" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qastle-{{ version }}.tar.gz
  sha256: 517075f4071bc5efe91670f6c21be2e60bea1ba9e5723e07a18111160e5377db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6,<3.13
    - pip
  run:
    - python >=3.6,<3.13
    - lark

test:
  imports:
    - qastle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iris-hep/qastle
  summary: Query AST Language Expressions
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/iris-hep/qastle

extra:
  recipe-maintainers:
    - masonproffitt
    - matthewfeickert
