{% set name = "qastle" %}
{% set version = "0.19.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qastle-{{ version }}.tar.gz
  sha256: ddb10c5a573a80f25470dfe5bf6e81d39b49a4f82b5eeca33f038cc5bea0feac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.14
    - lark

test:
  imports:
    - qastle
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/iris-hep/qastle
  summary: Query AST Language Expressions
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/iris-hep/qastle

extra:
  recipe-maintainers:
    - masonproffitt
    - matthewfeickert
